### ISSUE TITLE
[BUG] Upper method applied to each queried symbol...

### ISSUE THREAD

**Issue by hoangvictor** [pssolanki111/polygon#12]
I check the code and see that it uses upper() method after a string symbol, if we query some ticker like AAMpA, where there is a letter 'p' which is not in upper case, the result will be FALSE.

**Comment by Hoernchen** [comment]
Just managed to hit this with ABRpD..

**Comment by pssolanki111** [comment]
I remember this being reported once before and I think it should be possible to query a symbol without the lib changing it.

Lemme know if this is still an issue and I'll take a look
