### ISSUE TITLE
[Issue] Wrong underlying API call for get_macd 

### ISSUE THREAD

**Issue by svmlfin** [pssolanki111/polygon#14]
### Though it is suggested to follow the below structure to file an issue, feel free to use your own way to file issues too. Just ensure you're providing adequate information about the issue. That's all we'd need :)

**Describe the bug**
In get_macd function in the base client, ema is being called as the underlying API. https://github.com/pssolanki111/polygon/blob/84fe5dae48b7ea54d5c2d80e56cb20fac452457d/polygon/base_client.py#L780

**To Reproduce**
Calling SyncStocksClient.get_macd and SyncStocksClient.ema give the same results

**Comment by pssolanki111** [comment]
hey sorry for delay. Didn't get enough time due to my full time role. Thanks for the report.

I'll take a look and add it to the backlog

**Comment by pssolanki111** [comment]
@svmlfin This is fixed in version 1.1.2. Commit: https://github.com/pssolanki111/polygon/commit/d90ce4bd601ebb72dcfa1be6d1ef4da351c84109

Please upgrade the library (`pip install --upgrade polygon`)
