### ISSUE TITLE
Wrong order of the date in TOS

### ISSUE THREAD

**Issue by greko6** [pssolanki111/polygon#16]
Hello,

Great library! 

You have the wrong order of the option. Instead {dd}{mm}{yy}, it should be: {yy}{mm}{dd} for ThinkOrSwim (and potentially TDA?). 
Example that works in TOS: .PYPL231027P57, (not: .PYPL271023P57)

https://github.com/pssolanki111/polygon/blob/78c33dd0ab0f6e30e67b83d62ad9e5d47da9eae9/polygon/options/options.py#L12

Just letting you know!

**Comment by pssolanki111** [comment]
Thanks @greko6 

Interesting. The above format was given to me by some folks who used TOS and TDA. 
Would you mind joining the discord server to show a few examples from the TOS UI (or thinkScript)

(or share them here if you prefer)

**Comment by greko6** [comment]
Sure! Here are a few screenshots from TOS:

SPX:
![image](https://github.com/pssolanki111/polygon/assets/1009724/024cb62a-b264-4e5e-8f5a-f5563badd940)

AAPL:
![image](https://github.com/pssolanki111/polygon/assets/1009724/28a74fcf-d8a7-4e6f-9198-09dddf26e459)

TSLA:
![image](https://github.com/pssolanki111/polygon/assets/1009724/3a30cac0-e83d-40de-976c-6c4e6e58a6d6)

AMZN:
![image](https://github.com/pssolanki111/polygon/assets/1009724/28ec0173-4663-4ad2-b664-037e19cef692)

**Comment by pssolanki111** [comment]
Thanks @greko6 
appreciate it. Haven't had much time recently so sorry for the delays :D

For TDA API, the current format is correct (that's mentioned in their developer documentation). I'll try to cross verify the TOS format and then make a change in lib if required. 

Till then, you can simply use the `OptionSymbol` object to access relevant data (and format to any format that you prefer)

I might actually add ability to pass in a format string which will be used for a custom formatting.

**Comment by pssolanki111** [comment]
I've decided to make this change in the next release, as I could not find any pressing resource in favor of the current structure. Will be released today. Thanks for bringing this up @greko6 

**I will add this structure as `tos1` so that both the structures are allowed to be used. I'm sure there was a reason why the current structure was used
